### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by vishal1237** [GridProtectionAlliance/openPDC#130]
I have a Phasor Measurement Unit(PMU) connected to LAN. I want to view its data on OpenPDC software. But, after putting the appropriate IP, Device ID and Port, when I try to connect, the following error pops up:

"No connection could be made because the target machine actively refused it. 1 connection attempted"

I can ping my Device(PMU) from my PC and the PMU is time synced with IRIGB. My model is running on RT-LAB successfully.

**Comment by ritchiecarroll** [comment]
Have you tried connection with the PMU Connection Tester from the same machine?

https://github.com/GridProtectionAlliance/PMUConnectionTester/releases

Also, I am going to close this issue since it is more of a support issue and not a software problem.

Please feel free to get needed support help from our discussions board:

https://discussions.gridprotectionalliance.org/c/gpa-products/openpdc

Thanks!
Ritchie
