### ISSUE TITLE
Wrong inputs behavior

### ISSUE THREAD

**Issue by andresantos22** [GridProtectionAlliance/openPDC#144]
Hi, I have a strange behavior in my inputs - just seeing the values after clicking it as attached:

There are an OPENPDC 2.4.120 outputting values to an OPENPDC 2.9.42 inputs.

Thank you.

<img width="607" alt="openpdcbehavior" src="https://user-images.githubusercontent.com/26048590/154055939-f096543b-f0ef-4a5a-a3ee-fe735bc1c2ec.PNG">

**Comment by ritchiecarroll** [comment]
Is the strange behavior the only seeing data once they are selected to trend?

Values not showing up in the tree (left) and the red bubble are usually caused by a deviation in the clock of the device versus the local machine clock.

Either the time on your reporting device is way off - or your local machine clock is - or both.

FYI - you can adjust tolerances (lead and lag time, values in seconds) under the "Display Settings" dialog (link above the graph).
