### ISSUE TITLE
GRAFAN WITH OPEN PDC

### ISSUE THREAD

**Issue by mairaGEB** [GridProtectionAlliance/openPDC#152]
Hello We are starting to use the OPEN PDC software in our company as a pilot project. I would like to run GRAFANA statistics but unfortunately I could not establish a connection.

In the XML Configuration editor we have:
![image](https://user-images.githubusercontent.com/106610500/171226777-d36ee39c-2982-46fa-ae02-611d3448af8d.png)

I´m trying to connect with the URL http://localhost:6352/api/grafana/ but the webpage shows nothing 
![image](https://user-images.githubusercontent.com/106610500/171226951-e7d0cb27-f0c0-4ac0-a96b-5a557c6a09cf.png)

In the manage nodes in OPENPDC dont appear the url of grafana I dont know if it doesnt care.
![image](https://user-images.githubusercontent.com/106610500/171227532-a1d9cc74-f431-4f38-826d-10c414159b6f.png)

The active adapters in the software are

![image](https://user-images.githubusercontent.com/106610500/171227673-6058682e-87d4-4972-b76a-6243d29733cc.png)

Te version tha we intalled is openPDC v2.9.148,  I would appreciate if you help us to find the error of not being able to display the url.

Thanks in advantage

Maira Duarte

**Comment by ritchiecarroll** [comment]
openPDC doesn't automatically come installed with Grafana (this often confuses people since the openHistorian 2.0 does).

You will need to install Grafana separately, install the openHistorian Grafana plugin: https://grafana.com/grafana/plugins/gridprotectionalliance-openhistorian-datasource/

You would then configure the openHistorian Grafana data source with the URL you have been testing.

Hope that helps!

Thanks,
Ritchie
