### ISSUE TITLE
Archiving Data from OpenPDC (Linux) to Postgres 

### ISSUE THREAD

**Issue by Awsaf780** [GridProtectionAlliance/openPDC#154]
Hi, I am having a bit of trouble identifying where to make changes, so that data can be archived in a relational database. 
I have used the default local historian and can successfully write data to csv using the playback utility. But I want the OpenPDC to write data directly to a database, so that some other application can access it. 

Should the changes be made in the configuration database? If so, where?
(Platform is Linux)

**Comment by clackner-gpa** [comment]
Hi @Awsaf780,
Thanks for reaching out. If you are still having issues with this I would recommend looking at some of the posts in our forum:
https://discussions.gridprotectionalliance.org/t/ado-output-adapter-error-failed-to-initialize-adapter-not-connecting-to-mysql-database/152
https://discussions.gridprotectionalliance.org/t/openhistorian-historian-data-to-be-saved-into-rdbms-oracle-sql-server-using-adoadapters/565/4
https://discussions.gridprotectionalliance.org/t/unable-to-archive-pmu-data-stream-in-mysql-database/1034/10
You may find you will get a better response over there if you continue to have configuration issues as well.
Since this is not an issue in the codebase I will close this Issue, but feel free to engage us over at https://discussions.gridprotectionalliance.org/
